[package]
name = "action-driver"
version = "0.5.4"
edition = "2021"
publish = false

[dependencies]
action-span = { path = "../action-span" }
action-frontend = { path = "../action-frontend" }
action-codegen = { path = "../action-codegen" }
serde_json = { version = "1.0", optional = true }

[target.'cfg(windows)'.dependencies]
inkwell = { version = "0.9", default-features = false, features = ["llvm21-1", "target-x86"] }

[target.'cfg(not(windows))'.dependencies]
inkwell = { version = "0.9", default-features = false, features = ["llvm21-1", "target-x86", "target-aarch64", "target-webassembly"] }
