use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    generate_runtime_bitcode_embed();
}

/// Generate `OUT_DIR/action_runtime.bc` at compile time and embed via `include_bytes!`.
/// Skipped when building the helper itself (`ACTION_BUILDING_RUNTIME_BC`) to avoid recursion.
fn generate_runtime_bitcode_embed() {
    let out_dir = match std::env::var("OUT_DIR") {
        Ok(d) => PathBuf::from(d),
        Err(_) => return,
    };
    let embed_rs = out_dir.join("runtime_bc_embed.rs");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../runtime-bc-emit/");
    println!("cargo:rerun-if-changed=src/runtime_decl/");

    if std::env::var("ACTION_BUILDING_RUNTIME_BC").is_ok() {
        write_embed_none(&embed_rs);
        return;
    }

    match build_and_run_runtime_bc_helper(&out_dir, &embed_rs) {
        Ok(()) => {}
        Err(e) => {
            eprintln!(
                "cargo:warning=runtime bitcode embed failed ({e}); \
                 falling back to define_runtime_generate() at runtime"
            );
            write_embed_none(&embed_rs);
        }
    }
}

fn write_embed_none(embed_rs: &Path) {
    std::fs::write(
        embed_rs,
        "// @generated by build.rs — no prebuilt runtime bitcode\n\
         pub static EMBEDDED_RUNTIME_BC: Option<&'static [u8]> = None;\n",
    )
    .expect("write runtime_bc_embed.rs");
}

fn write_embed_some(embed_rs: &Path) {
    std::fs::write(
        embed_rs,
        "// @generated by build.rs\n\
         pub static EMBEDDED_RUNTIME_BC: Option<&'static [u8]> = \
         Some(include_bytes!(\"action_runtime.bc\"));\n",
    )
    .expect("write runtime_bc_embed.rs");
}

fn build_and_run_runtime_bc_helper(out_dir: &Path, embed_rs: &Path) -> Result<(), String> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").map_err(|e| e.to_string())?;
    let workspace_root = PathBuf::from(&manifest_dir)
        .parent()
        .and_then(|p| p.parent())
        .ok_or("action-codegen manifest path")?
        .to_path_buf();
    let profile = std::env::var("PROFILE").unwrap_or_else(|_| "debug".into());
    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".into());
    let emit_manifest = workspace_root.join("crates/runtime-bc-emit/Cargo.toml");
    let helper_target = out_dir.join("runtime_bc_helper_target");

    let mut build_cmd = Command::new(&cargo);
    build_cmd
        .current_dir(&workspace_root)
        .env("ACTION_BUILDING_RUNTIME_BC", "1")
        .env("CARGO_TARGET_DIR", &helper_target)
        .args([
            "build",
            "--manifest-path",
            emit_manifest.to_str().ok_or("non-UTF8 manifest path")?,
            "--quiet",
        ]);
    if profile != "debug" {
        build_cmd.arg("--profile").arg(&profile);
    }
    if let Ok(prefix) = std::env::var("LLVM_SYS_211_PREFIX") {
        build_cmd.env("LLVM_SYS_211_PREFIX", prefix);
    }

    let status = build_cmd
        .status()
        .map_err(|e| format!("failed to spawn cargo build: {e}"))?;
    if !status.success() {
        return Err("cargo build -p runtime-bc-emit failed".into());
    }

    let mut helper = helper_target.join(&profile).join("runtime-bc-emit");
    if cfg!(windows) && helper.extension().is_none() {
        helper.set_extension("exe");
    }
    if !helper.exists() {
        return Err(format!(
            "runtime-bc-emit binary not found at {}",
            helper.display()
        ));
    }

    let bc_path = out_dir.join("action_runtime.bc");
    let run_status = Command::new(&helper)
        .arg(&bc_path)
        .status()
        .map_err(|e| format!("failed to run {}: {e}", helper.display()))?;
    if !run_status.success() {
        return Err("runtime-bc-emit exited with non-zero status".into());
    }

    write_embed_some(embed_rs);
    Ok(())
}
