use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    configure_llvm_linking();
    generate_runtime_bitcode_embed();
    build_host_runtime_staticlib();
}

fn configure_llvm_linking() {
    if let Ok(prefix) = std::env::var("LLVM_SYS_211_PREFIX") {
        let lib_dir = Path::new(&prefix).join("lib");
        if lib_dir.exists() {
            if std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default() == "windows" {
                // Only enable /FORCE:UNRESOLVED when explicitly opted in via
                // ACTION_FORCE_LINK env var. Unconditional force-unresolved
                // masks real linker errors.
                if std::env::var("ACTION_FORCE_LINK").is_ok() {
                    println!("cargo:rustc-link-arg=/FORCE:UNRESOLVED");
                }
                println!("cargo:rustc-link-arg=/STACK:8388608");
            } else {
                println!("cargo:rustc-link-arg=-Wl,-rpath,{}", lib_dir.display());
            }
        }
    }

    println!("cargo:rerun-if-env-changed=LLVM_SYS_211_PREFIX");
    println!("cargo:rerun-if-env-changed=ACTION_FORCE_LINK");
}

/// Generate `OUT_DIR/action_runtime.bc` at compile time and embed via `include_bytes!`.
/// Skipped when building the helper itself (`ACTION_BUILDING_RUNTIME_BC`) to avoid recursion.
fn generate_runtime_bitcode_embed() {
    let out_dir = match std::env::var("OUT_DIR") {
        Ok(d) => PathBuf::from(d),
        Err(_) => return,
    };
    let embed_rs = out_dir.join("runtime_bc_embed.rs");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=crates/runtime-bc-emit/");
    println!("cargo:rerun-if-changed=src/codegen/runtime_decl/");

    if std::env::var("ACTION_BUILDING_RUNTIME_BC").is_ok() {
        write_embed_none(&embed_rs);
        return;
    }

    match build_and_run_runtime_bc_helper(&out_dir, &embed_rs) {
        Ok(()) => {}
        Err(e) => {
            eprintln!(
                "cargo:warning=runtime bitcode embed failed ({e}); \
                 falling back to define_runtime_generate() at runtime"
            );
            write_embed_none(&embed_rs);
        }
    }
}

fn write_embed_none(embed_rs: &Path) {
    std::fs::write(
        embed_rs,
        "// @generated by build.rs — no prebuilt runtime bitcode\n\
         pub static EMBEDDED_RUNTIME_BC: Option<&'static [u8]> = None;\n",
    )
    .expect("write runtime_bc_embed.rs");
}

fn write_embed_some(embed_rs: &Path) {
    std::fs::write(
        embed_rs,
        "// @generated by build.rs\n\
         pub static EMBEDDED_RUNTIME_BC: Option<&'static [u8]> = \
         Some(include_bytes!(\"action_runtime.bc\"));\n",
    )
    .expect("write runtime_bc_embed.rs");
}

fn build_and_run_runtime_bc_helper(out_dir: &Path, embed_rs: &Path) -> Result<(), String> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").map_err(|e| e.to_string())?;
    let profile = std::env::var("PROFILE").unwrap_or_else(|_| "debug".into());
    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".into());
    let emit_manifest = PathBuf::from(&manifest_dir).join("crates/runtime-bc-emit/Cargo.toml");
    // Separate target dir avoids contention with the outer `cargo build` artifact directory.
    let helper_target = out_dir.join("runtime_bc_helper_target");

    let mut build_cmd = Command::new(&cargo);
    build_cmd
        .current_dir(&manifest_dir)
        .env("ACTION_BUILDING_RUNTIME_BC", "1")
        .env("CARGO_TARGET_DIR", &helper_target)
        .args([
            "build",
            "--manifest-path",
            emit_manifest.to_str().ok_or("non-UTF8 manifest path")?,
            "--quiet",
        ]);
    if profile != "debug" {
        build_cmd.arg("--profile").arg(&profile);
    }
    if let Ok(prefix) = std::env::var("LLVM_SYS_211_PREFIX") {
        build_cmd.env("LLVM_SYS_211_PREFIX", prefix);
    }

    let status = build_cmd
        .status()
        .map_err(|e| format!("failed to spawn cargo build: {e}"))?;
    if !status.success() {
        return Err("cargo build -p runtime-bc-emit failed".into());
    }

    let mut helper = helper_target.join(&profile).join("runtime-bc-emit");
    if cfg!(windows) && helper.extension().is_none() {
        helper.set_extension("exe");
    }
    if !helper.exists() {
        return Err(format!(
            "runtime-bc-emit binary not found at {}",
            helper.display()
        ));
    }

    let bc_path = out_dir.join("action_runtime.bc");
    let run_status = Command::new(&helper)
        .arg(&bc_path)
        .status()
        .map_err(|e| format!("failed to run {}: {e}", helper.display()))?;
    if !run_status.success() {
        return Err("runtime-bc-emit exited with non-zero status".into());
    }

    write_embed_some(embed_rs);
    Ok(())
}

/// Build `libaction_host_rt.a` for AOT executable linking (JSON/HTTP/threading C ABI).
fn build_host_runtime_staticlib() {
    if std::env::var("ACTION_BUILDING_RUNTIME_BC").is_ok()
        || std::env::var("ACTION_BUILDING_HOST_RT").is_ok()
    {
        return;
    }

    let manifest_dir = match std::env::var("CARGO_MANIFEST_DIR") {
        Ok(d) => PathBuf::from(d),
        Err(_) => return,
    };
    let host_rt_manifest = manifest_dir.join("crates/host-rt/Cargo.toml");
    if !host_rt_manifest.exists() {
        return;
    }

    println!("cargo:rerun-if-changed=crates/host-rt/");
    println!("cargo:rerun-if-changed=src/runtime_json.rs");
    println!("cargo:rerun-if-changed=src/http_runtime.rs");
    println!("cargo:rerun-if-changed=src/runtime_threading.rs");

    let profile = if std::env::var("PROFILE").unwrap_or_default() == "release" {
        "release"
    } else {
        "debug"
    };
    let target_dir = std::env::var("CARGO_TARGET_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| manifest_dir.join("target"));

    let lib_path = target_dir.join(profile).join("libaction_host_rt.a");
    let sources = [
        host_rt_manifest.clone(),
        manifest_dir.join("src/runtime_json.rs"),
        manifest_dir.join("src/http_runtime.rs"),
        manifest_dir.join("src/runtime_threading.rs"),
    ];
    if lib_path.exists() && !host_rt_sources_changed(&lib_path, &sources) {
        return;
    }

    let mut cmd = Command::new("cargo");
    cmd.current_dir(&manifest_dir);
    cmd.env("ACTION_BUILDING_HOST_RT", "1");
    cmd.env("CARGO_TARGET_DIR", &target_dir);
    cmd.args(["build", "--manifest-path"])
        .arg(&host_rt_manifest);
    if profile == "release" {
        cmd.arg("--release");
    }

    let status = cmd.status();
    match status {
        Ok(s) if s.success() => {}
        Ok(s) => {
            eprintln!(
                "cargo:warning=action-host-rt build failed (exit {}); AOT --emit exe may fail to link",
                s.code().unwrap_or(-1)
            );
        }
        Err(e) => {
            eprintln!("cargo:warning=failed to spawn action-host-rt build: {e}");
        }
    }
}

fn host_rt_sources_changed(lib: &Path, sources: &[PathBuf]) -> bool {
    let Ok(lib_mtime) = std::fs::metadata(lib).and_then(|m| m.modified()) else {
        return true;
    };
    sources.iter().any(|src| {
        std::fs::metadata(src)
            .and_then(|m| m.modified())
            .map(|t| t > lib_mtime)
            .unwrap_or(true)
    })
}
