#!/usr/bin/env python3
"""Generate include/action_rt.h from runtime_decl LLVM symbol names."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUNTIME_DECL = ROOT / "crates/action-codegen/src/runtime_decl"
OUT = ROOT / "include/action_rt.h"

PAT = re.compile(r'"(action_[a-z0-9_]+)"')


def collect_symbols() -> list[str]:
    names: set[str] = set()
    for path in sorted(RUNTIME_DECL.glob("*.rs")):
        text = path.read_text(encoding="utf-8")
        names.update(PAT.findall(text))
    return sorted(names)


def emit_header(symbols: list[str]) -> str:
    lines = [
        "/* Auto-generated by scripts/generate_action_rt_header.py — do not edit. */",
        "#ifndef ACTION_RT_H",
        "#define ACTION_RT_H",
        "",
        "#include <stdint.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        "/* Opaque runtime handles */",
        "typedef void *action_rc_ptr;",
        "typedef void *action_list_ptr;",
        "typedef void *action_map_ptr;",
        "typedef void *action_string_ptr;",
        "",
    ]
    for name in symbols:
        if name.endswith("_free") or "dec" in name or "destroy" in name:
            ret = "void"
        elif any(
            name.endswith(s)
            for s in ("_len", "_size", "_count", "_hash", "_cmp", "_get", "_index")
        ) or name.startswith("action_rc_") and "inc" not in name and "dec" not in name:
            ret = "int64_t"
        elif name.startswith("action_bool_") or "_is_" in name:
            ret = "int32_t"
        else:
            ret = "void *"
        lines.append(f"{ret} {name}(void); /* stub — see runtime_decl for real signature */")
    lines.extend(
        [
            "",
            "#ifdef __cplusplus",
            "}",
            "#endif",
            "",
            "#endif /* ACTION_RT_H */",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    symbols = collect_symbols()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(emit_header(symbols), encoding="utf-8")
    print(f"Wrote {OUT} ({len(symbols)} symbols)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
