/* Auto-generated by scripts/generate_action_rt_header.py — do not edit. */
#ifndef ACTION_RT_H
#define ACTION_RT_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Opaque runtime handles */
typedef void *action_rc_ptr;
typedef void *action_list_ptr;
typedef void *action_map_ptr;
typedef void *action_string_ptr;

void * action_abs_f(void); /* stub — see runtime_decl for real signature */
void * action_clock_gettime(void); /* stub — see runtime_decl for real signature */
void * action_cond_broadcast(void); /* stub — see runtime_decl for real signature */
void action_cond_destroy(void); /* stub — see runtime_decl for real signature */
void * action_cond_init(void); /* stub — see runtime_decl for real signature */
void * action_cond_signal(void); /* stub — see runtime_decl for real signature */
void * action_cond_wait(void); /* stub — see runtime_decl for real signature */
void * action_file_append(void); /* stub — see runtime_decl for real signature */
void * action_file_close(void); /* stub — see runtime_decl for real signature */
void * action_file_delete(void); /* stub — see runtime_decl for real signature */
void * action_file_eof(void); /* stub — see runtime_decl for real signature */
void * action_file_exists(void); /* stub — see runtime_decl for real signature */
void * action_file_flush(void); /* stub — see runtime_decl for real signature */
void * action_file_open(void); /* stub — see runtime_decl for real signature */
void * action_file_read_bytes(void); /* stub — see runtime_decl for real signature */
void * action_file_read_line(void); /* stub — see runtime_decl for real signature */
void * action_file_seek(void); /* stub — see runtime_decl for real signature */
void * action_file_tell(void); /* stub — see runtime_decl for real signature */
void * action_file_write_bytes(void); /* stub — see runtime_decl for real signature */
void * action_float_to_string(void); /* stub — see runtime_decl for real signature */
void * action_ht_bulk_copy_active_slots(void); /* stub — see runtime_decl for real signature */
void * action_ht_contains(void); /* stub — see runtime_decl for real signature */
void * action_ht_create(void); /* stub — see runtime_decl for real signature */
void * action_ht_from_list(void); /* stub — see runtime_decl for real signature */
int64_t action_ht_get(void); /* stub — see runtime_decl for real signature */
void * action_ht_hash_str(void); /* stub — see runtime_decl for real signature */
void * action_ht_insert(void); /* stub — see runtime_decl for real signature */
int64_t action_ht_len(void); /* stub — see runtime_decl for real signature */
void * action_ht_rehash(void); /* stub — see runtime_decl for real signature */
void * action_ht_remove(void); /* stub — see runtime_decl for real signature */
void action_http_free(void); /* stub — see runtime_decl for real signature */
void * action_http_request(void); /* stub — see runtime_decl for real signature */
void * action_int_pow(void); /* stub — see runtime_decl for real signature */
void * action_int_to_string(void); /* stub — see runtime_decl for real signature */
void * action_json_as_bool(void); /* stub — see runtime_decl for real signature */
void * action_json_as_float(void); /* stub — see runtime_decl for real signature */
void * action_json_as_str(void); /* stub — see runtime_decl for real signature */
void action_json_free(void); /* stub — see runtime_decl for real signature */
int64_t action_json_get(void); /* stub — see runtime_decl for real signature */
void * action_json_get_idx(void); /* stub — see runtime_decl for real signature */
int64_t action_json_len(void); /* stub — see runtime_decl for real signature */
void * action_json_parse(void); /* stub — see runtime_decl for real signature */
void * action_json_stringify(void); /* stub — see runtime_decl for real signature */
void * action_json_type(void); /* stub — see runtime_decl for real signature */
void * action_lazylist_to_list(void); /* stub — see runtime_decl for real signature */
void * action_list_all_walk(void); /* stub — see runtime_decl for real signature */
void * action_list_all_walk_rec(void); /* stub — see runtime_decl for real signature */
void * action_list_any_walk(void); /* stub — see runtime_decl for real signature */
void * action_list_any_walk_rec(void); /* stub — see runtime_decl for real signature */
void * action_list_chunks(void); /* stub — see runtime_decl for real signature */
void * action_list_concat(void); /* stub — see runtime_decl for real signature */
void * action_list_contains(void); /* stub — see runtime_decl for real signature */
void * action_list_contains_walk(void); /* stub — see runtime_decl for real signature */
void * action_list_create(void); /* stub — see runtime_decl for real signature */
void * action_list_drop(void); /* stub — see runtime_decl for real signature */
void * action_list_filter_map_walk(void); /* stub — see runtime_decl for real signature */
void * action_list_filter_map_walk_rec(void); /* stub — see runtime_decl for real signature */
void * action_list_filter_walk(void); /* stub — see runtime_decl for real signature */
void * action_list_filter_walk_rec(void); /* stub — see runtime_decl for real signature */
void * action_list_find_leaf(void); /* stub — see runtime_decl for real signature */
void * action_list_find_walk(void); /* stub — see runtime_decl for real signature */
void * action_list_find_walk_rec(void); /* stub — see runtime_decl for real signature */
void * action_list_flatten(void); /* stub — see runtime_decl for real signature */
void * action_list_fold_walk(void); /* stub — see runtime_decl for real signature */
void * action_list_fold_walk_rec(void); /* stub — see runtime_decl for real signature */
int64_t action_list_get(void); /* stub — see runtime_decl for real signature */
void * action_list_get_cached(void); /* stub — see runtime_decl for real signature */
void * action_list_head(void); /* stub — see runtime_decl for real signature */
void * action_list_index_of(void); /* stub — see runtime_decl for real signature */
void * action_list_init(void); /* stub — see runtime_decl for real signature */
void * action_list_insert(void); /* stub — see runtime_decl for real signature */
void * action_list_insert_rec(void); /* stub — see runtime_decl for real signature */
void * action_list_last(void); /* stub — see runtime_decl for real signature */
int64_t action_list_len(void); /* stub — see runtime_decl for real signature */
void * action_list_map_filter_walk(void); /* stub — see runtime_decl for real signature */
void * action_list_map_filter_walk_rec(void); /* stub — see runtime_decl for real signature */
void * action_list_map_take_while_walk(void); /* stub — see runtime_decl for real signature */
void * action_list_map_take_while_walk_rec(void); /* stub — see runtime_decl for real signature */
void * action_list_map_walk(void); /* stub — see runtime_decl for real signature */
void * action_list_map_walk_rec(void); /* stub — see runtime_decl for real signature */
void * action_list_print(void); /* stub — see runtime_decl for real signature */
void * action_list_push(void); /* stub — see runtime_decl for real signature */
void * action_list_push_leaf(void); /* stub — see runtime_decl for real signature */
void * action_list_push_subtree(void); /* stub — see runtime_decl for real signature */
void * action_list_range(void); /* stub — see runtime_decl for real signature */
void * action_list_remove(void); /* stub — see runtime_decl for real signature */
void * action_list_reverse(void); /* stub — see runtime_decl for real signature */
void * action_list_set(void); /* stub — see runtime_decl for real signature */
void * action_list_set_rec(void); /* stub — see runtime_decl for real signature */
void * action_list_slice(void); /* stub — see runtime_decl for real signature */
void * action_list_sorted(void); /* stub — see runtime_decl for real signature */
void * action_list_sorted_by(void); /* stub — see runtime_decl for real signature */
int64_t action_list_sorted_cmp(void); /* stub — see runtime_decl for real signature */
void * action_list_split_at(void); /* stub — see runtime_decl for real signature */
void * action_list_tail(void); /* stub — see runtime_decl for real signature */
void * action_list_take(void); /* stub — see runtime_decl for real signature */
void * action_list_take_while_walk(void); /* stub — see runtime_decl for real signature */
void * action_list_take_while_walk_rec(void); /* stub — see runtime_decl for real signature */
void * action_list_unique(void); /* stub — see runtime_decl for real signature */
void * action_list_windows(void); /* stub — see runtime_decl for real signature */
int64_t action_list_with_index(void); /* stub — see runtime_decl for real signature */
void * action_list_zip(void); /* stub — see runtime_decl for real signature */
void * action_malloc_rc(void); /* stub — see runtime_decl for real signature */
void * action_map_contains(void); /* stub — see runtime_decl for real signature */
void * action_map_create(void); /* stub — see runtime_decl for real signature */
void * action_map_entries(void); /* stub — see runtime_decl for real signature */
int64_t action_map_get(void); /* stub — see runtime_decl for real signature */
void * action_map_insert(void); /* stub — see runtime_decl for real signature */
void * action_map_keys(void); /* stub — see runtime_decl for real signature */
void * action_map_remove(void); /* stub — see runtime_decl for real signature */
void * action_map_union(void); /* stub — see runtime_decl for real signature */
void * action_map_values(void); /* stub — see runtime_decl for real signature */
void * action_max_tree_height(void); /* stub — see runtime_decl for real signature */
void action_mutex_destroy(void); /* stub — see runtime_decl for real signature */
void * action_mutex_init(void); /* stub — see runtime_decl for real signature */
void * action_mutex_lock(void); /* stub — see runtime_decl for real signature */
void * action_mutex_unlock(void); /* stub — see runtime_decl for real signature */
void * action_parse_int(void); /* stub — see runtime_decl for real signature */
void * action_pow(void); /* stub — see runtime_decl for real signature */
void * action_print_bool(void); /* stub — see runtime_decl for real signature */
void * action_print_enum(void); /* stub — see runtime_decl for real signature */
void * action_print_enum_float(void); /* stub — see runtime_decl for real signature */
void * action_print_float(void); /* stub — see runtime_decl for real signature */
void * action_print_int(void); /* stub — see runtime_decl for real signature */
void * action_print_string(void); /* stub — see runtime_decl for real signature */
void * action_print_struct(void); /* stub — see runtime_decl for real signature */
void * action_print_task(void); /* stub — see runtime_decl for real signature */
void * action_println(void); /* stub — see runtime_decl for real signature */
void * action_rand_float(void); /* stub — see runtime_decl for real signature */
void * action_rand_int(void); /* stub — see runtime_decl for real signature */
void * action_rand_seed(void); /* stub — see runtime_decl for real signature */
void * action_rand_shuffle(void); /* stub — see runtime_decl for real signature */
void action_rc_dec(void); /* stub — see runtime_decl for real signature */
void action_rc_dec_ht(void); /* stub — see runtime_decl for real signature */
void action_rc_dec_list_node(void); /* stub — see runtime_decl for real signature */
void * action_rc_inc(void); /* stub — see runtime_decl for real signature */
void * action_read_file(void); /* stub — see runtime_decl for real signature */
void * action_runtime(void); /* stub — see runtime_decl for real signature */
void * action_set_difference(void); /* stub — see runtime_decl for real signature */
void * action_set_from_list(void); /* stub — see runtime_decl for real signature */
void * action_set_intersection(void); /* stub — see runtime_decl for real signature */
int32_t action_set_is_subset(void); /* stub — see runtime_decl for real signature */
void * action_set_union(void); /* stub — see runtime_decl for real signature */
void * action_sleep_us(void); /* stub — see runtime_decl for real signature */
void * action_string_chars(void); /* stub — see runtime_decl for real signature */
void * action_string_concat(void); /* stub — see runtime_decl for real signature */
void * action_string_contains(void); /* stub — see runtime_decl for real signature */
void * action_string_create(void); /* stub — see runtime_decl for real signature */
void * action_string_data(void); /* stub — see runtime_decl for real signature */
void * action_string_data_ptr(void); /* stub — see runtime_decl for real signature */
void * action_string_ends_with(void); /* stub — see runtime_decl for real signature */
void * action_string_eq(void); /* stub — see runtime_decl for real signature */
void * action_string_index_of(void); /* stub — see runtime_decl for real signature */
int32_t action_string_is_slice(void); /* stub — see runtime_decl for real signature */
void * action_string_join(void); /* stub — see runtime_decl for real signature */
int64_t action_string_len(void); /* stub — see runtime_decl for real signature */
void action_string_rc_dec(void); /* stub — see runtime_decl for real signature */
void * action_string_rc_inc(void); /* stub — see runtime_decl for real signature */
void * action_string_repeat(void); /* stub — see runtime_decl for real signature */
void * action_string_replace(void); /* stub — see runtime_decl for real signature */
void * action_string_split(void); /* stub — see runtime_decl for real signature */
void * action_string_split_lines(void); /* stub — see runtime_decl for real signature */
void * action_string_starts_with(void); /* stub — see runtime_decl for real signature */
void * action_string_substring(void); /* stub — see runtime_decl for real signature */
void * action_string_to_lower(void); /* stub — see runtime_decl for real signature */
void * action_string_to_upper(void); /* stub — see runtime_decl for real signature */
void * action_string_trim(void); /* stub — see runtime_decl for real signature */
void * action_string_trim_end(void); /* stub — see runtime_decl for real signature */
void * action_string_trim_start(void); /* stub — see runtime_decl for real signature */
void * action_test_ping(void); /* stub — see runtime_decl for real signature */
void * action_thread_cancel(void); /* stub — see runtime_decl for real signature */
void * action_thread_create(void); /* stub — see runtime_decl for real signature */
void * action_thread_detach(void); /* stub — see runtime_decl for real signature */
void * action_thread_join(void); /* stub — see runtime_decl for real signature */
int64_t action_utf8_byte_len(void); /* stub — see runtime_decl for real signature */
void * action_utf8_encode(void); /* stub — see runtime_decl for real signature */
void * action_write_file(void); /* stub — see runtime_decl for real signature */

#ifdef __cplusplus
}
#endif

#endif /* ACTION_RT_H */
